







	



.build/nano328/hx711/hx711.d : lib/hx711/hx711.cpp
	@mkdir -p .build/nano328/hx711
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/eightanaloginputs -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/hx711 -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/EEPROM  -MM $^ > $@
	
	@printf ".build/nano328/hx711/hx711.d .build/nano328/hx711/" | cat - $@ > $@~ && mv $@~ $@



.build/nano328/hx711/dependencies.d : .build/nano328/hx711/hx711.d
	@echo [96mScanning dependencies of hx711[0m
	@mkdir -p .build/nano328/hx711
	@cat $^ > $@;

all : .build/nano328/hx711/dependencies.d
	@true

